name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install npm-run-all

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          command: npm run build:and:test
          browser: chrome
